name: db_client
description: A Dart package for ODBC databases. Supports concurrent connections, proper resource management, and works reliably under load.
version: 0.2.1
repository: https://github.com/macss-dev/db_client.git

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  windows:
  linux:
  macos:

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  ffigen: ^13.0.0
  lints: ^4.0.0
  test: ^1.28.0
  very_good_analysis: ^6.0.0

topics:
  - sql
  - odbc
  - sqlserver
  - oracle
